# Generated by Django 2.2.4 on 2019-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('position_name', models.CharField(max_length=100)),
                ('hireDate', models.DateField()),
                ('fireDate', models.DateField(null=True)),
                ('salary', models.IntegerField()),
                ('fraction', models.IntegerField()),
                ('base', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('by_hours', models.BooleanField()),
            ],
        ),
    ]
