# Generated by Django 2.2.4 on 2019-08-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='advance',
            field=models.IntegerField(verbose_name='Аванс, руб.'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='base',
            field=models.IntegerField(verbose_name='База, руб.'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='by_hours',
            field=models.BooleanField(verbose_name='Почасовая оплата'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='fireDate',
            field=models.DateField(null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='fraction',
            field=models.IntegerField(verbose_name='Ставка, %'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='hireDate',
            field=models.DateField(verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='position_name',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='salary',
            field=models.IntegerField(verbose_name='Ставка, руб.'),
        ),
    ]
