# Generated by Django 2.2.4 on 2019-08-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0004_auto_20190815_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupation',
            options={'ordering': ['-name'], 'verbose_name': 'Работника', 'verbose_name_plural': 'Работники'},
        ),
    ]
