# Generated by Django 2.2.4 on 2019-08-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0005_auto_20190815_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='company_name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='position_name',
            new_name='positionName',
        ),
    ]
